name: Build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: imhele/wattsi
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: docker build
      run: make docker
    - name: docker tag
      run: |
        docker tag "$IMAGE_NAME" "$IMAGE_NAME:$(cat src/version.inc)"
        docker tag "$IMAGE_NAME" "$IMAGE_NAME:latest"
    - name: docker login
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: docker push
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        docker push "$IMAGE_NAME:$(cat src/version.inc)"
        docker push "$IMAGE_NAME:latest"
